-- Crear Tablas sin relaciones
CREATE TABLE ROLES (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    nombre VARCHAR2(50) NOT NULL,
    PRIMARY KEY(id)
)

-- Crear Tablas con relaciones
CREATE TABLE PERMISOS (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    id_rol NUMBER NOT NULL,
    leer NUMBER NOT NULL,
    escribir NUMBER NOT NULL,
    eliminar NUMBER NOT NULL,
    modificar NUMBER NOT NULL,
    tabla VARCHAR2(50),
    PRIMARY KEY(id),
    CONSTRAINT fk_rol FOREIGN KEY (id_rol) REFERENCES ROLES(id)
)

CREATE TABLE USUARIOS (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY,
  id_rol NUMBER NOT NULL,
  nombre VARCHAR2(50) NOT NULL,
  email VARCHAR2(50) NOT NULL,
  contrasena VARCHAR2(50) NOT NULL,
  PRIMARY KEY(id),
  CONSTRAINT fk_rol_user FOREIGN KEY (id_rol) REFERENCES ROLES(id)
)

CREATE TABLE HORARIOS_USUARIOS (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY,
  id_usuario NUMBER NOT NULL,
  nombre VARCHAR2(50) NOT NULL,
  PRIMARY KEY(id),
  CONSTRAINT fk_usuario_HORARIOS_USUARIOS FOREIGN KEY (id_usuario) REFERENCES USUARIOS(id)
)

CREATE TABLE MATERIAS (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY,
  id_horario NUMBER NOT NULL,
  nombre VARCHAR2(50) NOT NULL,
  color VARCHAR2(50) NOT NULL,
  PRIMARY KEY(id),
  CONSTRAINT fk_horario_materia FOREIGN KEY (id_horario) REFERENCES HORARIOS_USUARIOS(id)
)

CREATE TABLE DETALLES_MATERIAS (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY,
  id_materia NUMBER NOT NULL,
  descripcion VARCHAR2(50) NOT NULL,
  mostrar NUMBER NOT NULL,
  PRIMARY KEY(id),
  CONSTRAINT fk_materia_detalles FOREIGN KEY (id_materia) REFERENCES MATERIAS(id)
)

CREATE TABLE HORARIOS (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY,
  id_materia NUMBER NOT NULL,
  dia VARCHAR2(1) NOT NULL,
  hora_incio VARCHAR2(5) NOT NULL,
  hora_fin VARCHAR2(5) NOT NULL,
  PRIMARY KEY(id),
  CONSTRAINT fk_materia_horarios FOREIGN KEY (id_materia) REFERENCES MATERIAS(id)
)
  
CREATE TABLE DETALLES_HORARIOS (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY,
  id_horario NUMBER NOT NULL,
  descripcion VARCHAR2(50) NOT NULL,
  mostrar NUMBER NOT NULL,
  PRIMARY KEY(id),
  CONSTRAINT fk_horario_detalles FOREIGN KEY (id_horario) REFERENCES HORARIOS(id)
)

CREATE TABLE COMPARTIR_HORARIO (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY,
  url_acesso VARCHAR2(50) NOT NULL, 
  id_horario NUMBER NOT NULL,
  PRIMARY KEY(id),
  CONSTRAINT fk_horario_compartir FOREIGN KEY (id_horario) REFERENCES HORARIOS_USUARIOS(id)
)

CREATE TABLE COMENTARIOS_HORARIO (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY,
  id_horario NUMBER NOT NULL,
  id_usuario NUMBER NOT NULL,
  comentario VARCHAR2(255) NOT NULL,
  publicado DATE NOT NULL,
  PRIMARY KEY(id),
  CONSTRAINT fk_horario_comentarios FOREIGN KEY (id_horario) REFERENCES HORARIOS_USUARIOS(id)
)

-- Insertar roles
INSERT INTO ROLES (nombre) VALUES ('Administrador');
INSERT INTO ROLES (nombre) VALUES ('Profesor');
INSERT INTO ROLES (nombre) VALUES ('Estudiante');

-- Insertar permisos
INSERT INTO PERMISOS (id_rol, leer, escribir, eliminar, modificar, tabla) VALUES (1, 1, 1, 1, 1, 'USUARIOS');
INSERT INTO PERMISOS (id_rol, leer, escribir, eliminar, modificar, tabla) VALUES (2, 1, 1, 0, 1, 'MATERIAS');
INSERT INTO PERMISOS (id_rol, leer, escribir, eliminar, modificar, tabla) VALUES (3, 1, 0, 0, 0, 'HORARIOS');

-- Insertar usuarios
INSERT INTO USUARIOS (id_rol, nombre, email, contrasena) VALUES (1, 'Admin', 'admin@email.com', 'admin123');
INSERT INTO USUARIOS (id_rol, nombre, email, contrasena) VALUES (2, 'Profesor Juan', 'juan@email.com', 'profesor123');
INSERT INTO USUARIOS (id_rol, nombre, email, contrasena) VALUES (3, 'Estudiante Ana', 'ana@email.com', 'estudiante123');

-- Insertar horarios de usuarios
INSERT INTO HORARIOS_USUARIOS (id_usuario, nombre) VALUES (2, 'Horario Profesor Juan');
INSERT INTO HORARIOS_USUARIOS (id_usuario, nombre) VALUES (3, 'Horario Estudiante Ana');

-- Insertar materias
INSERT INTO MATERIAS (id_horario, nombre, color) VALUES (1, 'Matemáticas', 'Azul');
INSERT INTO MATERIAS (id_horario, nombre, color) VALUES (2, 'Historia', 'Rojo');

-- Insertar detalles de materias
INSERT INTO DETALLES_MATERIAS (id_materia, descripcion, mostrar) VALUES (1, 'Álgebra y Cálculo', 1);
INSERT INTO DETALLES_MATERIAS (id_materia, descripcion, mostrar) VALUES (2, 'Historia Universal', 1);

-- Insertar horarios
INSERT INTO HORARIOS (id_materia, dia, hora_incio, hora_fin) VALUES (1, 'L', '08:00', '10:00');
INSERT INTO HORARIOS (id_materia, dia, hora_incio, hora_fin) VALUES (2, 'M', '10:00', '12:00');

-- Insertar detalles de horarios
INSERT INTO DETALLES_HORARIOS (id_horario, descripcion, mostrar) VALUES (1, 'Clase en Aula 101', 1);
INSERT INTO DETALLES_HORARIOS (id_horario, descripcion, mostrar) VALUES (2, 'Clase en Aula 202', 1);

-- Insertar compartir horario
INSERT INTO COMPARTIR_HORARIO (url_acesso, id_horario) VALUES ('https://mis-horarios.com/juan', 1);
INSERT INTO COMPARTIR_HORARIO (url_acesso, id_horario) VALUES ('https://mis-horarios.com/ana', 2);

-- Insertar comentarios sobre horarios
INSERT INTO COMENTARIOS_HORARIO (id_horario, id_usuario, comentario, publicado) VALUES (1, 3, 'Muy buena clase de matemáticas', SYSDATE);
INSERT INTO COMENTARIOS_HORARIO (id_horario, id_usuario, comentario, publicado) VALUES (2, 3, 'La historia es interesante', SYSDATE);
